#H2 Server Properties
#Tue Dec 24 14:58:38 EST 2024
0=JHipster H2 (Disk)|org.h2.Driver|jdbc\:h2\:file\:./target/h2db/db/jhipstersampleonlinestore|JhipsterSampleOnlineStore
webSSL=false
webAllowOthers=true
webPort=8092
